### ISSUE TITLE
运行闪退

### ISSUE THREAD

**Issue by KOFKOY** [dyhkwong/SagerNet#20]
安卓10，运行最新版0.10.8， 下载订阅后开启代理闪退
E  FATAL EXCEPTION: main
                                                                                                    Process: com.github.sagernet.sagernet, PID: 20483
                                                                                                    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}; have you declared this activity in your AndroidManifest.xml?
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2079)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5436)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
                                                                                                    	at androidx.activity.ComponentActivity$activityResultRegistry$1.onLaunch(SourceFile:166)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$register$2.launch(SourceFile:102)
                                                                                                    	at io.nekohasekai.sagernet.ui.MainActivity.onCreate$lambda$0(SourceFile:23)
                                                                                                    	at io.nekohasekai.sagernet.ui.MainActivity.$r8$lambda$m_HH_D7rPWTHhuKd_s6gnf2kt4U(SourceFile:1)
                                                                                                    	at io.nekohasekai.sagernet.ui.MainActivity$$ExternalSyntheticLambda3.onClick(SourceFile:1)
                                                                                                    	at android.view.View.performClick(View.java:7509)
                                                                                                    	at android.view.View.performClickInternal(View.java:7486)
                                                                                                    	at android.view.View.access$3600(View.java:841)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28710)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8060)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

好像是没声明VPN权限

**Comment by KOFKOY** [comment]
红米k20pro  MIUI 12.5.6。是系统的问题吗，试了v2rayng ， clash meta for android 都不行，只有之前的clash for android可以
